#! /bin/sh


sxhkd &

# launchers
nm-applet &
wal -R &
xrdb -merge ~/.Xresources &
xbindkeys --poll-rc &
compton -bc &
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
dropbox &
aria2c &


## PyWal config

# source the colors
. $HOME/.cache/wal/colors.sh

# set border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

# for bspwm > 0.9.4
bspc config presel_feedback_color "$color1"


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# mice bindings
#

# set windows key as pointer_modifier
# use xmodmap to view the keys
bspc config pointer_modifier mod4

# focus follows the pointer
bspc config focus_follows_pointer true

# set mouse 1 to move floating windows
bspc config pointer_action1 move

# mouse 2 button resizes by side
bspc config pointer_action2 resize_side

# mouse 3 button (right mouse) resizes by corner
bspc config pointer_action3 resize_corner